steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/testgo', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/testgo']
images: ['gcr.io/${PROJECT_ID}/testgo']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'kube/thai-test.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=thai-test-slot-cluster-1'
logsBucket: 'gs://credit-net-test/BankData'
options:
  logging: GCS_ONLY
